export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';
export const REQUEST_LIST_PENDING = 'REQUEST_LIST_PENDING';
export const REQUEST_LIST_SUCCESS = 'REQUEST_LIST_SUCCESS';
export const REQUEST_LIST_FAILED = 'REQUEST_LIST_FAILED';